name: USDT CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        gcc-version: [ 10, 11, 12, 13, 14 ]
        shared: [ 0, 1 ]

    name: gcc-${{ matrix.gcc-version }} SHARED=${{ matrix.shared }}

    env:
      GCC_VERSION: ${{ matrix.gcc-version }}
      SHARED: ${{ matrix.shared }}

    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisites
      run: sudo -E .github/scripts/setup.sh

    - name: Build SHARED=${{ matrix.shared }}
      run: .github/scripts/build.sh

    - name: Test SHARED=${{ matrix.shared }}
      run: make -C tests test
