name: USDT CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisites
      run: |
        curl -L -o bpftrace https://github.com/bpftrace/bpftrace/releases/download/v0.21.2/bpftrace
        chmod +x bpftrace
        ./bpftrace --version

    - name: Build (static)
      run: make SHARED=0 -C tests -j$(nproc) build

    - name: Build (shared)
      run: make SHARED=1 -C tests -j$(nproc) build

    - name: Test (static)
      run: make V=1 BPFTRACE=$(realpath bpftrace) BPFTRACE_TIMEOUT=300 SHARED=0 -C tests test

    - name: Test (shared)
      run: make V=1 BPFTRACE=$(realpath bpftrace) BPFTRACE_TIMEOUT=300 SHARED=1 -C tests test
